first

diff --git a/ansible/roles/eks/tasks/main.yml b/ansible/roles/eks/tasks/main.yml
--- a/ansible/roles/eks/tasks/main.yml
+++ b/ansible/roles/eks/tasks/main.yml
@@ -106,43 +106,61 @@
 
 - name: Create EKS cluster
   shell: |
+    set -e
     if ! aws eks describe-cluster --name {{ cluster_name }} --region {{ region }} >/dev/null 2>&1; then
+      echo "Creating cluster..."
       aws eks create-cluster \
         --name {{ cluster_name }} \
         --version {{ kubernetes_version }} \
         --role-arn arn:aws:iam::{{ ansible_account_id }}:role/{{ cluster_name }}-cluster-role \
         --resources-vpc-config subnetIds={{ public_subnets.results[0].subnet.id }},{{ public_subnets.results[1].subnet.id }},{{ private_subnets.results[0].subnet.id }},{{ private_subnets.results[1].subnet.id }} \
         --region {{ region }}
-      echo "CREATED"
+      if [ $? -eq 0 ]; then
+        echo "CREATED"
+      else
+        echo "FAILED"
+        exit 1
+      fi
     else
       echo "EXISTS"
     fi
   register: cluster_result
 
+- name: Debug cluster creation result
+  debug:
+    var: cluster_result
+
 - name: Wait for EKS cluster to be active
   shell: aws eks wait cluster-active --name {{ cluster_name }} --region {{ region }}
-  when: cluster_result.stdout == "CREATED" or cluster_result.stdout == "EXISTS"
+  when: cluster_result.stdout_lines | last == "CREATED" or cluster_result.stdout_lines | last == "EXISTS"
 
 - name: Create EKS node group
   shell: |
-    if ! aws eks describe-nodegroup --cluster-name {{ cluster_name }} --nodegroup-name {{ node_group_name }} --region {{ region }} >/dev/null 2>&1; then
-      aws eks create-nodegroup \
-        --cluster-name {{ cluster_name }} \
-        --nodegroup-name {{ node_group_name }} \
-        --node-role arn:aws:iam::{{ ansible_account_id }}:role/{{ cluster_name }}-node-role \
-        --subnets {{ private_subnets.results[0].subnet.id }} {{ private_subnets.results[1].subnet.id }} \
-        --instance-types {{ node_instance_type }} \
-        --scaling-config minSize={{ node_min_size }},maxSize={{ node_max_size }},desiredSize={{ node_desired_capacity }} \
-        --region {{ region }}
-      echo "CREATED"
+    set -e
+    if aws eks describe-cluster --name {{ cluster_name }} --region {{ region }} >/dev/null 2>&1; then
+      if ! aws eks describe-nodegroup --cluster-name {{ cluster_name }} --nodegroup-name {{ node_group_name }} --region {{ region }} >/dev/null 2>&1; then
+        echo "Creating nodegroup..."
+        aws eks create-nodegroup \
+          --cluster-name {{ cluster_name }} \
+          --nodegroup-name {{ node_group_name }} \
+          --node-role arn:aws:iam::{{ ansible_account_id }}:role/{{ cluster_name }}-node-role \
+          --subnets {{ private_subnets.results[0].subnet.id }} {{ private_subnets.results[1].subnet.id }} \
+          --instance-types {{ node_instance_type }} \
+          --scaling-config minSize={{ node_min_size }},maxSize={{ node_max_size }},desiredSize={{ node_desired_capacity }} \
+          --region {{ region }}
+        echo "CREATED"
+      else
+        echo "EXISTS"
+      fi
     else
-      echo "EXISTS"
+      echo "CLUSTER_NOT_FOUND"
+      exit 1
     fi
   register: nodegroup_result
 
 - name: Wait for node group to be active
   shell: aws eks wait nodegroup-active --cluster-name {{ cluster_name }} --nodegroup-name {{ node_group_name }} --region {{ region }}
-  when: nodegroup_result.stdout == "CREATED" or nodegroup_result.stdout == "EXISTS"
+  when: nodegroup_result.stdout_lines | last == "CREATED" or nodegroup_result.stdout_lines | last == "EXISTS"
 
 - name: Generate kubeconfig
   shell: |
